# Generated by Django 4.2 on 2023-05-07 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 12, 53, 11, 890714)),
        ),
    ]
